In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
import os

In [5]:
# Import required libraries for downloading and extracting
import urllib.request
import zipfile
import os

# Dataset URL
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00240/UCI%20HAR%20Dataset.zip"

# File name to save
zip_path = "har_dataset.zip"

# Download the dataset
urllib.request.urlretrieve(url, zip_path)

print("Download complete.")

# Extract the dataset
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("har_data")

print("Extraction complete.")

Download complete.
Extraction complete.

In [6]:
X_train=pd.read_csv("har_data/UCI HAR Dataset/train/X_train.txt", delim_whitespace=True, header=None)

/tmp/ipykernel_3283/831468100.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  X_train=pd.read_csv("har_data/UCI HAR Dataset/train/X_train.txt", delim_whitespace=True, header=None)

In [7]:
y_train=pd.read_csv("har_data/UCI HAR Dataset/train/y_train.txt", delim_whitespace=True, header=None).iloc[:,0] - 1 #to make the labels start from 0 instead of 1
X_test=pd.read_csv("har_data/UCI HAR Dataset/test/X_test.txt", delim_whitespace=True, header=None)
y_test=pd.read_csv("har_data/UCI HAR Dataset/test/y_test.txt", delim_whitespace=True, header=None).iloc[:,0] - 1 #to make the labels start from 0 instead of 1

/tmp/ipykernel_3283/1623746817.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  y_train=pd.read_csv("har_data/UCI HAR Dataset/train/y_train.txt", delim_whitespace=True, header=None).iloc[:,0] - 1 #to make the labels start from 0 instead of 1
/tmp/ipykernel_3283/1623746817.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  X_test=pd.read_csv("har_data/UCI HAR Dataset/test/X_test.txt", delim_whitespace=True, header=None)
/tmp/ipykernel_3283/1623746817.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  y_test=pd.read_csv("har_data/UCI HAR Dataset/test/y_test.txt", delim_whitespace=True, header=None).iloc[:,0] - 1 #to make the labels start from 0 instead of 1

In [8]:
print(X_train.isna().sum())
print(y_train.isna().sum())
print(X_test.isna().sum())
print(y_test.isna().sum())

0      0
1      0
2      0
3      0
4      0
      ..
556    0
557    0
558    0
559    0
560    0
Length: 561, dtype: int64
0
0      0
1      0
2      0
3      0
4      0
      ..
556    0
557    0
558    0
559    0
560    0
Length: 561, dtype: int64
0

In [9]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,551,552,553,554,555,556,557,558,559,560
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.074323,-0.298676,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,0.158075,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,0.414503,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,0.404573,-0.117290,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,0.087753,-0.351471,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7347,0.299665,-0.057193,-0.181233,-0.195387,0.039905,0.077078,-0.282301,0.043616,0.060410,0.210795,...,-0.070157,-0.588433,-0.880324,-0.190437,0.829718,0.206972,-0.425619,-0.791883,0.238604,0.049819
7348,0.273853,-0.007749,-0.147468,-0.235309,0.004816,0.059280,-0.322552,-0.029456,0.080585,0.117440,...,0.165259,-0.390738,-0.680744,0.064907,0.875679,-0.879033,0.400219,-0.771840,0.252676,0.050053
7349,0.273387,-0.017011,-0.045022,-0.218218,-0.103822,0.274533,-0.304515,-0.098913,0.332584,0.043999,...,0.195034,0.025145,-0.304029,0.052806,-0.266724,0.864404,0.701169,-0.779133,0.249145,0.040811
7350,0.289654,-0.018843,-0.158281,-0.219139,-0.111412,0.268893,-0.310487,-0.068200,0.319473,0.101702,...,0.013865,0.063907,-0.344314,-0.101360,0.700740,0.936674,-0.589479,-0.785181,0.246432,0.025339
7351,0.351503,-0.012423,-0.203867,-0.269270,-0.087212,0.177404,-0.377404,-0.038678,0.229430,0.269013,...,-0.058402,-0.387052,-0.740738,-0.280088,-0.007739,-0.056088,-0.616956,-0.783267,0.246809,0.036695

In [10]:
y_train

0       4
1       4
2       4
3       4
4       4
       ..
7347    1
7348    1
7349    1
7350    1
7351    1
Name: 0, Length: 7352, dtype: int64

In [11]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [12]:
X_train=X_train_scaled[:,:20] #replaces the feature selection process for session purpose
X_test=X_test_scaled[:,:20] #replaces the feature selection process for session purpose

In [13]:
y_train.shape

(7352,)

In [14]:
model=keras.Sequential([
    keras.layers.Dense(256,activation="relu", input_shape=(20,)),
    keras.layers.Dense(128,activation="relu"),
    keras.layers.Dense(64,activation="relu"),
    keras.layers.Dense(16,activation="relu"),
    keras.layers.Dense(8,activation="relu"),
    keras.layers.Dense(6,activation="softmax")
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 256)            │         5,376 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 6)              │            54 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 47,758 (186.55 KB)

 Trainable params: 47,758 (186.55 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test))

Epoch 1/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.4853 - loss: 1.0752 - val_accuracy: 0.5277 - val_loss: 0.9091
Epoch 2/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5475 - loss: 0.8434 - val_accuracy: 0.5148 - val_loss: 0.9089
Epoch 3/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5831 - loss: 0.8045 - val_accuracy: 0.6135 - val_loss: 0.8686
Epoch 4/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6179 - loss: 0.7579 - val_accuracy: 0.6060 - val_loss: 0.8785
Epoch 5/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6427 - loss: 0.7154 - val_accuracy: 0.6050 - val_loss: 0.8160
Epoch 6/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6785 - loss: 0.6764 - val_accuracy: 0.6865 - val_loss: 0.7252
Epoch 7/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7005 - loss: 0.6348 - val_accuracy: 0.6624 - val_loss: 0.8314
Epoch 8/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7073 - loss: 0.6164 - val_accuracy: 0.6267 - val_loss: 0.8024
Epoch 9/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7220 - loss: 0.5902 - val_accuracy: 0.7021 - val_loss: 0.7130
Epoch 10/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7235 - loss: 0.5925 - val_accuracy: 0.7058 - val_loss: 0.7619
Epoch 11/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7325 - loss: 0.5814 - val_accuracy: 0.6882 - val_loss: 0.7646
Epoch 12/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7512 - loss: 0.5543 - val_accuracy: 0.6983 - val_loss: 0.8017
Epoch 13/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7594 - loss: 0.5366 - val_accuracy: 0.6994 - val_loss: 0.7859
Epoch 14/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7439 - loss: 0.5457 - val_accuracy: 0.7248 - val_loss: 0.7238
Epoch 15/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7591 - loss: 0.5240 - val_accuracy: 0.7248 - val_loss: 0.7661
Epoch 16/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7631 - loss: 0.5192 - val_accuracy: 0.7153 - val_loss: 0.7311
Epoch 17/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7797 - loss: 0.4898 - val_accuracy: 0.6916 - val_loss: 0.7900
Epoch 18/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7779 - loss: 0.4893 - val_accuracy: 0.7122 - val_loss: 0.7948
Epoch 19/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7802 - loss: 0.4894 - val_accuracy: 0.7241 - val_loss: 0.8320
Epoch 20/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7807 - loss: 0.4837 - val_accuracy: 0.6888 - val_loss: 0.8674
Epoch 21/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7856 - loss: 0.4763 - val_accuracy: 0.7133 - val_loss: 0.8610
Epoch 22/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7912 - loss: 0.4690 - val_accuracy: 0.6851 - val_loss: 0.8873
Epoch 23/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7807 - loss: 0.4791 - val_accuracy: 0.7031 - val_loss: 0.8716
Epoch 24/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7935 - loss: 0.4674 - val_accuracy: 0.7007 - val_loss: 0.8671
Epoch 25/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7900 - loss: 0.4594 - val_accuracy: 0.7058 - val_loss: 0.8504
Epoch 26/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7950 - loss: 0.4583 - val_accuracy: 0.7055 - val_loss: 0.8809
Epoch 27/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8025 - loss: 0.4402 - val_accuracy: 0.6468 - val_loss: 1.0058
Epoch 28/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8013 - loss: 0.4476 - val_accuracy: 0.7061 - val_loss: 0.9301
Epoch 29/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8010 - loss: 0.4415 - val_accuracy: 0.7255 - val_loss: 0.8548
Epoch 30/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7979 - loss: 0.4503 - val_accuracy: 0.7082 - val_loss: 0.9240
Epoch 31/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7980 - loss: 0.4409 - val_accuracy: 0.6542 - val_loss: 0.9889
Epoch 32/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8097 - loss: 0.4233 - val_accuracy: 0.7173 - val_loss: 0.9488
Epoch 33/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8112 - loss: 0.4170 - val_accuracy: 0.7156 - val_loss: 0.9627
Epoch 34/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8124 - loss: 0.4144 - val_accuracy: 0.6671 - val_loss: 1.0819
Epoch 35/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8077 - loss: 0.4314 - val_accuracy: 0.7058 - val_loss: 1.0175
Epoch 36/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8124 - loss: 0.4214 - val_accuracy: 0.7211 - val_loss: 0.9976
Epoch 37/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8077 - loss: 0.4281 - val_accuracy: 0.7302 - val_loss: 1.0180
Epoch 38/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8166 - loss: 0.4009 - val_accuracy: 0.6766 - val_loss: 1.1267
Epoch 39/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8188 - loss: 0.4044 - val_accuracy: 0.6647 - val_loss: 1.1383
Epoch 40/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8153 - loss: 0.4116 - val_accuracy: 0.6488 - val_loss: 1.1264
Epoch 41/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8164 - loss: 0.4014 - val_accuracy: 0.7089 - val_loss: 1.0114
Epoch 42/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8198 - loss: 0.3937 - val_accuracy: 0.6882 - val_loss: 1.1769
Epoch 43/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8221 - loss: 0.3961 - val_accuracy: 0.7044 - val_loss: 1.0446
Epoch 44/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8266 - loss: 0.3839 - val_accuracy: 0.7089 - val_loss: 1.0708
Epoch 45/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8244 - loss: 0.3950 - val_accuracy: 0.7126 - val_loss: 1.0735
Epoch 46/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8264 - loss: 0.3852 - val_accuracy: 0.6949 - val_loss: 1.2299
Epoch 47/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8298 - loss: 0.3785 - val_accuracy: 0.6990 - val_loss: 1.1827
Epoch 48/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8251 - loss: 0.3917 - val_accuracy: 0.6970 - val_loss: 1.0972
Epoch 49/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8300 - loss: 0.3848 - val_accuracy: 0.7044 - val_loss: 1.1626
Epoch 50/50
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8259 - loss: 0.3796 - val_accuracy: 0.7072 - val_loss: 1.2142

In [18]:
converter=tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model=converter.convert()

with open("model.tflite", "wb") as f:
    f.write(tflite_model)

Saved artifact at '/tmp/tmpi48iiiht'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 20), dtype=tf.float32, name='keras_tensor')
Output Type:
  TensorSpec(shape=(None, 6), dtype=tf.float32, name=None)
Captures:
  138134394226832: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394227984: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394226640: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394225104: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394228560: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394226256: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394226064: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394228368: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394228944: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394227792: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394229904: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394227024: TensorSpec(shape=(), dtype=tf.resource, name=None)

In [19]:
converter=tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations=[tf.lite.Optimize.DEFAULT]
tflite_model_quant=converter.convert()

Saved artifact at '/tmp/tmpd_52bcz3'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 20), dtype=tf.float32, name='keras_tensor')
Output Type:
  TensorSpec(shape=(None, 6), dtype=tf.float32, name=None)
Captures:
  138134394226832: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394227984: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394226640: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394225104: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394228560: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394226256: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394226064: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394228368: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394228944: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394227792: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394229904: TensorSpec(shape=(), dtype=tf.resource, name=None)
  138134394227024: TensorSpec(shape=(), dtype=tf.resource, name=None)

In [20]:
with open("model_quant.tflite", "wb") as f:
    f.write(tflite_model_quant)

In [21]:
print("original model size:", os.path.getsize("model.tflite")/1024, "Kbytes")
print("quantized model size:", os.path.getsize("model_quant.tflite")/1024, "Kbytes")

original model size: 189.7265625 Kbytes
quantized model size: 57.265625 Kbytes

In [22]:
interpreter=tf.lite.Interpreter(model_path="model_quant.tflite")
interpreter.allocate_tensors()

/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/interpreter.py:457: UserWarning:     Warning: tf.lite.Interpreter is deprecated and is scheduled for deletion in
    TF 2.20. Please use the LiteRT interpreter from the ai_edge_litert package.
    See the [migration guide](https://ai.google.dev/edge/litert/migration)
    for details.

  warnings.warn(_INTERPRETER_DELETION_WARNING)

In [23]:
input_details=interpreter.get_input_details()
output_details=interpreter.get_output_details()

In [24]:
sample=np.array([X_test[0]], dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], sample)
interpreter.invoke()

In [25]:
output=interpreter.get_tensor(output_details[0]['index'])

In [26]:
print('Predicted class:', np.argmax(output))

Predicted class: 4

In [27]:
print(y_test[0])

4